const quizData = [
    {
    question: "CSS stands for -",
    a: "Cascade style sheets",
    b: "Color and style sheets",
    c: "Cascading style sheets",
    d: "None of the above",
    correct: "c",
},
    {
    question: "Which of the following is the correct syntax to display the hyperlinks without any underline?",
    a: "a {text-decoration : underline;}",
    b: "a {decoration : no-underline;}",
    c: "a {text-decoration : none;}",
    d: "None of the above",
    correct: "c",
},
    {
    question: "The CSS property used to specify the transparency of an element is -",
    a: "opacity",
    b: "filter",
    c: "visibility",
    d: "overlay",
    correct: "a",
},
    {
    question: "The CSS property used to specify whether the text is written in the horizontal or vertical direction?",
    a: "text-indent",
    b: "writing-mode",
    c: "word-break",
    d: "None of the above",
    correct: "b",
},
    {
    question: "Which of the following syntax is correct in CSS to make each word of a sentence start with a capital letter?",
    a: "text-style : capital;",
    b: "transform : capitalize;",
    c: "text-transform : capital;",
    d: "text-transform : capitalize;",
    correct: "d",
},
//     {
//     question: "",
//     a: "",
//     b: "",
//     c: "",
//     d: "",
//     correct: "",
// },
];